### ISSUE TITLE
Give Admin better/more perms on WA

### ISSUE THREAD

**Issue by NoLongerTipsy** [Nimtrod/Nimtrod-s-To-Do#15]
Force tpying is a must have especially when they are offline, it feels like we are powerless to help players or maintain server, acts like we havent been opped

**Comment by N0tMyFaultOG** [comment]
Indeed, a while back I added a plugin to queue up commands which will execute onJoin.
Typing `/q` will show this overview:
![](https://i.imgur.com/OR9xuLE.png)
If you want to tp an offline player to spawn, you type `/q add <player> <command>`
You need to keep in mind that these commands run via console so you need to provide everything in the <command> section. You want to tp me to spawn, you need to type `/q add NotMyFault spawn NotMyFault`. Put the full command behind the playername. If the player is online and you type the command, it gets executed immediately.

**Comment by N0tMyFaultOG** [comment]
The perms for /q only work in lowercase. I just tested it out with SirNumcelot and it works fine now. Also you should be able to bypass the tp cd anyway. But you can use commands like `/tpo` or `/tpohere` so you don't have a cooldown in general.

**Comment by NoLongerTipsy** [comment]
Thanks for the info :)
