### ISSUE TITLE
/glist showall not showing WA

### ISSUE THREAD

**Issue by NoLongerTipsy** [Nimtrod/Nimtrod-s-To-Do#8]

**Comment by N0tMyFaultOG** [comment]
![](https://i.imgur.com/fCLmhlu.png)
Works perfectly fine now. Sometimes if the Redis instance goes down or has a huge latency, stuff like `!chat` or any other command associated with Redis (`/glist`, `/plist`) stop working. A restart of the affected proxy will solve it.

**Comment by NoLongerTipsy** [comment]
Agreed i noticed this was back to normal last night
